# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-28 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_student_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name=b'Status')),
                ('date', models.DateField(blank=True, verbose_name=b'Date')),
                ('name', models.ForeignKey(max_length=256, on_delete=django.db.models.deletion.CASCADE, to='students.Student', verbose_name=b'Student name')),
            ],
            options={
                'verbose_name': 'Journal',
            },
        ),
    ]
