# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-28 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_journal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline_name', models.CharField(max_length=256, verbose_name=b'Discipline name')),
                ('date', models.DateTimeField(verbose_name=b'Date')),
                ('teacher_name', models.CharField(max_length=256, verbose_name=b'Teacher name')),
                ('group_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='students.Group', verbose_name=b'Group')),
            ],
        ),
    ]
