# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-28 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20170128_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(verbose_name=b'Rating')),
                ('date', models.DateField(verbose_name=b'Date')),
            ],
            options={
                'verbose_name': 'Exam Result',
                'verbose_name_plural': 'Exam Results',
            },
        ),
        migrations.AlterField(
            model_name='exam',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Group', verbose_name=b'Group'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='exam_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='students.Exam', verbose_name=b'Exam'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='student_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='students.Student', verbose_name=b'Student'),
        ),
    ]
