# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-04 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20170128_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Additional notices'),
        ),
    ]
