# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-09 03:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20170204_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='discipline_name',
            field=models.CharField(max_length=256, verbose_name='Discipline name'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='teacher_name',
            field=models.CharField(max_length=256, verbose_name='Teacher name'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='exam_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='students.Exam', verbose_name='Exam'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='rating',
            field=models.FloatField(verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='student_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='students.Student', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='date',
            field=models.DateField(blank=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='name',
            field=models.ForeignKey(max_length=256, on_delete=django.db.models.deletion.CASCADE, to='students.Student', verbose_name='Student name'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto'),
        ),
    ]
